
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'
    - 'app/pdfs/internship_pdf.rb' #Internship


# Internship refactoring dependent marked with #Internship
# those should eventually be deleted or fixed: marked with #TBD
Metrics/AbcSize:
  Exclude:
    - 'db/seed/lib/08_lib.rb' #Internship
    - 'app/admin'
    - 'app/controllers/internships_controller.rb'
    - 'app/models/ability.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/admin/internships/internships_form.rb' #Internship
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'spec/factories/*'
    - 'app/admin/**/*.rb'
    - 'app/admin/internships/internships_show.rb'
    - 'app/controllers/internships_controller.rb'


Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'
    - 'db/seed/lib/08_lib.rb' #Internship
    - 'app/controllers/favorite_controller.rb' # delete?
    - 'app/controllers/finish_list_controller.rb' # delete?
    - 'app/controllers/internships_controller.rb'
