# Internship refactoring dependent marked with #Internship
# those should eventually be deleted or fixed: marked with #TBD

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'
    - 'app/pdfs/internship_pdf.rb' #Internship

Layout/LineLength:
  Exclude:
    - 'config/initializers/new_framework_defaults_6_0.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/admin'
    - 'db/seed/08_lib/08_internships.rb' #Internship

Metrics/BlockLength:
  Exclude:
    - 'app/admin/internships/internships_form.rb' #Internship
    - 'config/**/*'
    - 'spec/**/*' # DSL
    - 'spec-api/**/*'
    - 'config/routes.rb'
    - 'spec/factories/*'
    - 'app/admin/**/*.rb'
    - 'app/admin/internships/internships_show.rb'
    - 'app/controllers/internships_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/internships_controller.rb'
    - 'db/seed/08_lib/08_internships.rb' #Internship

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/internships_controller.rb' #Internship
    - 'app/controllers/searches_controller.rb' #Search

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/searches_helper.rb' #Search


Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
# TBD: Enable New Cops one by one
Gemspec/DateAssignment: # (new in 1.10)
  Enabled: false
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: false
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: false
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: false
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: false
Lint/EmptyBlock: # (new in 1.1)
  Enabled: false
Lint/EmptyClass: # (new in 1.3)
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: false
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: false
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: false
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: false
Lint/SymbolConversion: # (new in 1.9)
  Enabled: false
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: false
Lint/TripleQuotes: # (new in 1.9)
  Enabled: false
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: false
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: false
Style/CollectionCompact: # (new in 1.2)
  Enabled: false
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: false
Style/EndlessMethod: # (new in 1.8)
  Enabled: false
Style/HashConversion: # (new in 1.10)
  Enabled: false
Style/HashExcept: # (new in 1.7)
  Enabled: false
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: false
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: false
Style/NilLambda: # (new in 1.3)
  Enabled: false
Style/RedundantArgument: # (new in 1.4)
  Enabled: false
Style/StringChars: # (new in 1.12)
  Enabled: false
Style/SwapValues: # (new in 1.1)
  Enabled: false
