# Internship refactoring dependent marked with #Internship
# those should eventually be deleted or fixed: marked with #TBD

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'
    - 'app/pdfs/internship_pdf.rb' #Internship

Layout/LineLength:
  Exclude:
    - 'config/initializers/new_framework_defaults_6_0.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/admin'
    - 'db/seed/08_lib/08_internships.rb' #Internship

Metrics/BlockLength:
  Exclude:
    - 'app/admin/internships/internships_form.rb' #Internship
    - 'config/**/*'
    - 'spec/**/*' # DSL
    - 'spec-api/**/*'
    - 'config/routes.rb'
    - 'spec/factories/*'
    - 'app/admin/**/*.rb'
    - 'app/admin/internships/internships_show.rb'
    - 'app/controllers/internships_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/internships_controller.rb'
    - 'db/seed/08_lib/08_internships.rb' #Internship

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/internships_controller.rb' #Internship
    - 'app/controllers/searches_controller.rb' #Search

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/searches_helper.rb' #Search


Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
