
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'

# Internship refactoring dependent marked with #Internship
# those should eventually be deleted or fixed: marked with #TBD
Metrics/AbcSize:
  Exclude:
    - 'db/seed/lib/08_lib.rb' #Internship
    - 'app/admin'

Metrics/BlockLength:
  Exclude:
    - app/admin/internships/internships_form.rb #Internship
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'spec/factories/*'
    - 'app/admin/*'

Metrics/ClassLength:
  Exclude:
    - 'app/pdfs/internship_pdf.rb' #Internship


Metrics/MethodLength:
  Exclude:
    - 'db/seed/lib/08_lib.rb' #Internship
