
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'
Metrics/AbcSize:
  Exclude:
    - 'app/admin'

# those should eventually be deleted or fixed.

Style/MethodMissingSuper:
  Exclude:
    - 'app/helpers/rating_renderer.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/factories/*'
    - 'app/admin/*'
