# use this to see a clean rubocop.
# should be commented out as it also hides new violations -
# to check remove the #
# inherit_from: .rubocop_todo.yml

# db/seed/lib/08_lib.rb: depends on Internship too heavy.

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'
Metrics/AbcSize:
  Exclude:
    - 'app/admin'
    - 'db/seed/lib/08_lib.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/seed/lib/08_lib.rb'

# those should eventually be deleted or fixed.

Style/MethodMissingSuper:
  Exclude:
    - 'app/helpers/rating_renderer.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/factories/*'
    - 'app/admin/*'
Metrics/ClassLength:
  Exclude:
    - 'app/pdfs/internship_pdf.rb'
