language: ruby
sudo: required
services:
- docker
rvm:
  - 2.4.1
before_install:
- gem install bundler
- bundle --version
install:
- echo "Install task"
- gem install thor
script:
- "./ci-cd/travis-test.sh"
env:
  matrix:
  - "IMIMAPS_ENVIRONMENT=docker"
  - "IMIMAPS_ENVIRONMENT=local"
  global:
    # DOCKER_USERNAME
    - secure: "V5HR+I5Owf+zkjEZuzuhelwLagmGLlFns/Z1Oec5NBq3EoTek9rKT5hDMDZT81wrgFVInAdEKUNW3iQ2bIGDB4AkTa9Db2KtYzkeHG1rniHkc7n3GA8IxlR1NtKxZKwAWQr3Mf1hcUFWJWsQJymJK/FKaitfL6DT7nKuovKFfruX5mhW283q7lSKQm3kWewq1q2HKXJuJVo6TJCHDhwwebbmphDfp1X2ATgq2xQjpxrBjJGT5ysdC9THWHRpx1FAvfSg+aOLBs+STsB4YeUfGnaKwcUdV5LZIwJoG4qxtnooUDHXBtSvfifdy05kGXpVTMgFDvdYlXjrtgm++0ZC8jrXQUNX+CZ7ituX3Q3UwCeJVVVSMMW2KfdhMbKW3YMrlLnGgN5U9GH4af2v54Hi6im5lMA2zddqValT/SH3WEv28wU2FoDviZlHv4YIk5byNrX6kQfnvydURcar3hzllCc2dQ46KYFB301GtSRB7sbPrq+icsLokj8zpTxFt4BbC0jTLGMmGclX8JYrbVpU3AbGPWaqi/3DSAjEnCKfc5yV0Z+WKlbwcSG3mTTSDe94rb8N0hgfyql/kFQmxYPZoWnT4ssdcJLeuMloxhWwDojUOVrDmGirKG7JNnMxz8l4nU6F18vVxYB8zr1Xti6Za4zC6S/TOZdhHs1/C9jZ4Ho="
    # DOCKER_PASSWORD
    - secure: "rhiUywSLbmsruuAG2AN21wGjBVwBZdx6cpxCg1Qx2GAVHKbLp3FrLh3ndKL6yFmx/1yrj1ljemf0XhGaGF1xbq43kigTmXsGTDG5KSwxeyZ/ZhNEsghu6+vyTSbhyaFzi0+8+Gcon6D3b/Mhy8SVdAk717n7eLrOTQrj+KoRPcGtOf9k5vNtcYVKkTnd8Hccf0GjPpPHJLKp4y83bwLw2HqGjDdrpoaOnv3DAZavoZAR/pMDGmImaY0AGrVAxryo/7G6IcagfgF5sf5DPQJfQ8DpiiOLtmnKkWPvFhYYs3zsYVs/0EfZuvZXaeBp5Y80uC1LHXvQHk9oqYSo439gNXyU9KsBTpwFbUu9VrUfwnPu9Lk79B/I2cGJyHbi7cVH3yFFKxW7Kg9sX8N9UlWnv0aB3dky0yqo+3aqurk3qJRBprTnxP2QH5LCWAYxuWBsHo/cJ6hRUZk1x/3B/x6mWXxLr6t1kU6dMTIvavfIz7KbFwFcmDkAAgc5IFae0xDFAy1n2okC4BztdJtni/S22IugL7D7LMqph35exKrb/UjeJ3zR/WpjBAZvd6r4zDYcMWEqPd80iXeSPDV6dYXxXnpzkgy48ENO1PC96N/7VHSe2AuaBUd+fTvseYIyHoUncBlpiP228AMYeo8swHOIBcS4yqdwxpaukriSMxfWSpw="
jobs:
  include:
    - stage: decrypt keys
      install: true # hopefully skips install
      script: ci-cd/deploy03-travis-decrypt-keys.sh
      env: "IMIMAPS_ENVIRONMENT=docker"
      rvm: 2.4.1
    - stage: deploy to staging
      script: "./ci-cd/travis-deploy.sh staging"
      env: "IMIMAPS_ENVIRONMENT=docker"
      rvm: 2.4.1
    - stage: deploy to production
      script: "./ci-cd/travis-deploy.sh production"
      env: "IMIMAPS_ENVIRONMENT=docker"
      rvm: 2.4.1
  allow_failures:
    - stage: decrypt keys
      env: "IMIMAPS_ENVIRONMENT=docker"
      rvm: 2.4.1
    - stage: deploy to staging
      env: "IMIMAPS_ENVIRONMENT=docker"
      rvm: 2.4.1
    - stage: deploy to production
      env: "IMIMAPS_ENVIRONMENT=docker"
      rvm: 2.4.1
# how to allow failures in stages:
# https://github.com/backspace/travixperiments-redux/blob/primary/.travis.yml
# https://github.com/travis-ci/beta-features/issues/11#issuecomment-301310134
