language: generic
sudo: required
services:
- docker
before_script:
  - sudo /etc/init.d/postgresql stop
script:
- "./ci-cd/travis-test.sh"
env:
  global:
  - IMIMAPS_ENVIRONMENT=docker
jobs:
  include:
  - stage: test
    script: "./ci-cd/travis-test.sh"
  - stage: build
    script: ci-cd/docker-build-and-push.sh
    if: ((tag IS present) OR (branch = master))
#    if: ((tag IS present) OR (branch = master)) AND (type != pull_request)
  - stage: deploy-staging
    script: "./ci-cd/travis-deploy.sh staging"
    if: ( NOT (tag IS present)) AND (branch = master) AND (type != pull_request)
  - stage: deploy-production
    script: "./ci-cd/travis-deploy.sh production"
    if: (tag IS present) AND (type != pull_request)
