language: generic
sudo: required
services:
- docker
before_script:
  - sudo /etc/init.d/postgresql stop
script:
- "./ci-cd/travis-test.sh"
env:
  global:
  - IMIMAPS_ENVIRONMENT=docker
  - secure: jCAXaoxiBIABJmzEDEeIGb7IHhQL/j1sUjoR95Exi5fn2XhMg2WNlDufdh+c4AHA1dWlNoVB7HRjrw3WazO7vQhelLbY+B+U2VTAvQ7UpYZw2yjxQXl5uyDfCKJu5d9mVjjGSTmpj2VNHsKgnR7UG8xWcGRtFHePDsYcrdpZ3mmaDH4WwBzmsADY4oRKkwtm+EtbZ9E0zJCIog0mIbButWo4NB9dnlqLVgw3gNMMxwvvxZFuQHoFS1NDXby3o+BB/Gs2zmDVm4SxdqnGO/OA7rLTaLMRYo8CAN5s/0jK9Kkh7qZswiRH9wY/yfF5gXR65UKYqyomMtFubCqdbDt6xoB9er7EGji/4v6cAAynxfnVAahBtTZrx80h26aYgsfSChjR+bS52Qf5KyYOstZpT/81PKMWqxfLjpQwPLl8TJkTbvSsRGLoYxRO/NeCxlmEQY3SbqPCUfbT90kWzARQKIFatx6m1joSb4sn2BVmsq4+5WCWDltubI636wr7Z5X/nnzPyVBj9qjEHQAa/148+6AOdtwjnM6WUfzPTFk1NvmzTQor2m4Mw158jB+fShpmyOTZSZvv7A3Ec3LwmWaDPQ/ERS2X3WTf+ZzA5KCHwmTbhCMgn1q0p4zZeVjKx6vFh1xow5M9dz02928qD/iOcbkgFI46S8hyjdGJiHWLaXQ=
  - secure: TaKtPIzpgOiHJJ+DeekEK1+Q1t/r3h7uTWWqN1p0Zrx1wlDPDgAk6wlipu45hf6ff2FNu/XkKp3Cw5IgYyVpGBSDvccWNwv4Xcz9BLlg1/7ne7T+gwOUzQYPWe4pm8BEUvTsZx1J9EpFUC6IGVLN60t2sAimcMRDqfSwdWm9z9hvaRzTwQ9t6uiOzt9ZAOdbAcHHoG0A5OqAWCpMApzeijtZsKN5HEKePQis3S4blMmWqdrGlsJHYIv2rzzr6azMXydEvXsW2lDx4Krhpjepo4uCr5lGGv9bRu5jkpIl8vSuoDy3zAukUgclj0fvWBeBEgYb9DloTv3GDpTB5LHBtq9YqyuAsR6WH/jQRvhYo1lICqpMD/u3dFPDTsNg03t0/0E0xKgC7xeBACYzlfa1Y7xtnqTk6Rd0zq4hjHnb9ytp2CpKisuW9wI62vPMi+1c+0inNyo6X3+0gH6XGjMubZicmzvpweijtxu0UYRR0tSeWMz9waA8GBMfQJpVtUvSAhkKa4mpIFYYgzLh7ZqJpK4N6ExSitK9z6q/GKlxh3uOAy0UXTGZdEeGUuRabMaGOfV7kto3CMe+t12cQtLofgFNPW6dGOZp2y6EvgK3DeZWChUKtxKglsZekh19qmXNJ+E2cjMhK+eROVFFBvZkYKuqCsgw3sEtbYX56ChUzX4=
  - secure: FUrsJFCahj2NK6MpMxQBVG9avWCoREQTSo80CDfTOS4JCOEhMZxYjmUc7GHN33LiaPQ2PrMc0k95HhkEk+MiJUbph/QpO1aTJBRaBG6ibB94gNxTE2vTV+MB68f8xQ4zoWn/JiK73oqWeEcSlQw7fKEb4WpEiKh0jM1UR8muImUPuu8FDQ1z6IJLMUld1M7Saev8jy1ZUzZELynaE9YakCOWJwFlRFmiCFMiITWrXIrR8Pp7Kdtn/L+Z67+diLB1AE6MkjDwT+zES3ET9Yy1DDV+8py9Ms0C1UspQiTLHmhEHCVL0wzzPx2flwsqsQdCTwocNFsgaJMVlUx2SbGr5ndr1v3U3U3qSb2b3t1h0se66Wjuys5pLVYKHzb1jzV5hhVzw+f3A0m9TJ5/WxGp7/f415q2dMssnL8WGoJDzk3rr0GtpLlZTpK5KNQ0KjGldGeFYNPPg3SjaS0afmFXja5kZeZGnkW3TcXgYKo6qKXj1A4RBYMzywVXm6399zc4r0sWDv7gj9NQq5urhAyeGwO2UUBreNeD+CEI6vcjYCkwmHLJrH1PngcM2WpOJmJZ7Hh27eonBAVkU7j1V0ptU/rXUug8jS/KreKTgUPISLpem6cbYTK5/EzrHY/Zc5zH5C80DkIXiol7fC064qMIAS/6NKN8pBIo79EPv/oWPkQ=
stages:
  - test
  - name: docker-build
    if: (branch = travis-stages) AND (NOT (type IN (push, pull_request)))
  - name: deploy-staging
    if: (branch = travis-stages) AND (NOT (type IN (push, pull_request)))
  - name: deploy-production
    if: (tag =~ ^v1) AND (branch = master) AND (NOT (type IN (push, pull_request)))
jobs:
  include:
  - stage: test
    script: "./ci-cd/travis-test.sh"
  - stage: build and push docker image
    script: ci-cd/docker-build-and-push.sh
  - stage: deploy to staging
    script: "./ci-cd/travis-deploy.sh staging"
  - stage: deploy to production
    script: "./ci-cd/travis-deploy.sh production"
