sudo: required
services:
- docker
language: ruby
rvm:
- 2.1.5
install:
- echo "Install task"
- gem install thor
script:
- echo "Build start"
- ./docker-tool test start
- echo "Build done"
before_install:
  - openssl aes-256-cbc -K $encrypted_473888976053_key -iv $encrypted_473888976053_iv -in ssh_keys.tar.enc -out ssh_keys.tar -d
  - tar xvf ssh_keys.tar
  - chmod 0600 id_rsa*
after_success:
- "./ci-cd/docker-build.rb"
- "./ci-cd/docker-push.rb"
- "./ci-cd/docker-deploy.rb"
env:
  global:
    # DOCKER_USERNAME
    - secure:  "MOQjdz+V+VcdrA3P0L/EXGf8Y7Xb7q8cqNMVc95lz3q2VshHQFlB087GCtpRdYbscveGSkkq6hCnbjCa0r2fZ4EMBkcRtF/SzPzrShudc40sbZO87FLAeKdFpceYuc8cVhbu9VUMTXECafi+eLDToI1PwbMFfxh5HzWoHraXFvGuQx/EdeWMfbjPohttICQ2gwv1Ty0EfqLbSDEwFuqTSSrDbwUeiIt+s7AZxLyF33g7aPlI/+aTJI/XouRkooHxh1F0wsxb/iJYSlNYp3vZnQ8uneFCVz49EQ2+DYf59E53qU/xtnd+LF9NTpzKkfXkThUAbmT3SaNJM1wOV5IXfUMHIRZ568Nd7+1ctlCMkfouuI4foECcRNa7IwRjB/lJLMCzcnPMFeFQJxQJHVVL5Ud9euaI8DEBy20+NRGvngRCgu7s6Kt1Z+uZayp5Lte1iELxaAlmGGQDRAB4izpm1MIbjJ06yJqBNfKbatXdOo6G93SJNlffqvRaK2P08Ur0EdOXUI1kyOaiQnDJUrwcl3FmWE0ei9YP6anFFiCDHtjASTNPuKJotPj1KAH5pa0Z5z9oKBy6iccRFDL9DstMd4XO4KMGVtAyYSC89zHF6xhyFmUUiBsJYz7aGzbob9/qRDjcUVlU3jW+4uZahpnxGDD6Q7KLTs0fFeQ1zfrKjcU="
    # DOCKER_PASSWORD
    - secure: "rZmvyQpRNNpU3yE1L3MzGZOA6Kdy10GJtq+wv1Tp24zwB2dRcPrm3uKNIuJeLxY7JVbuwi+swquMxAmBtl+14h5YFrmNysNp84gynr0D5vO9u8RwPo2ghlxINLWors03u2whGKne83SxE5iW7P16iP09Wvmv5JhUhlDlnFLlhzSISEPrch+wh7Vp8IoKfaHKkk4ERvCsjxKRtbUARCGjelZT7m4zUwFpl5QiXmWpayA48kzKzCx5SAODgyQXp6spbtFP+QafTgTQQmhbdnKKQxBPEAGSEN1/uXRhl3y7LTBmikbZXKPmPUndgtZgwZumDRSGtCNp58Q6y2ImrJxd0xtCJ6VNTFREKjeUduZMeOSL9oZxoFdQ5A11K7+KwB6KeKtr4RKGp6Z0BRL15FtiKw7yMrDFcUlQd5zaa4bMk+92A7QQw78z+eji3ub6YCBfVqTZ5coga911Vsd1VBiagY2kgzsKgBWdqFHfiTaccxk5TEy+23hcNlg3wnOe9vR4kAWH16tUBQkqTcHC3/kxoDfnp1FZUMBMwFYhWExpVyOWbKZJzT+hw3ChizZb4NSC0ujycoqruTYGQzbsFFFJqTIzRlAIdZbmcHmOacc/oUDsPuO5VqTmUyIWLqNdkNZ4ZlHf/iqlrgt5DRVFuWBVMNR/g1yfSsHNCfVTwICBJRw="
