version: '3'
services:
  postgresql:
    image: postgres:9.6.2-alpine
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imi_map_production
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always

  imimap:
    image: imimap/imimap:${TAG}
    container_name: imimap
    environment:
      - TAG
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imi_map_production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=true
    depends_on:
      - postgresql
    links:
      - postgresql
    ports:
      - 4000:80
#    volumes:
#      - ./rails/public:/usr/src/app/nginx-assets
#      - ./rails/public:/usr/src/app/public/assets
    restart: always
