version: '3'
services:
  postgresql:
    image: postgres:9.6.2-alpine
    container_name: postgresql-dev
    environment:
      - APPLICATION=imimap
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imimap
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/dumps:/var/lib/postgresql/dumps
    ports:
      - 5432:5432

  imimap:
    build: .
    image: imimap:dev
    container_name: imimap-dev
    environment:
      - APPLICATION=imimap
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imimap
      - LDAP=${LDAP}
    depends_on:
      - postgresql
    volumes:
      - .:/usr/src/app
    links:
      - postgresql
    ports:
      - 8080:80
