version: '3'
services:
  postgresql:
    image: postgres:13.1-alpine
    container_name: postgresql-dev
    environment:
      - APPLICATION=imimap
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imimap
    ports:
      - 5432:5432
  imimap:
    build: .
    image: imimap:dev
    container_name: imimap-dev
    environment:
      - APPLICATION=imimap
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imimap
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - LDAP=${LDAP}
    depends_on:
      - postgresql
    volumes:
      - ./logc:/usr/src/app/log
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    links:
      - postgresql
    ports:
      - 8080:80
    stdin_open: true
    tty: true
