version: '3'
services:
  postgresql:
    image: postgres:13.1-alpine
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imi_map_production
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/dumps:/var/lib/postgresql/dumps
    restart: always
  imimap:
    image: imimap/imimap:${TAG}
    container_name: imimap
    environment:
      - TAG
      - POSTGRES_PASSWORD=imimap
      - POSTGRES_USER=imi_map
      - POSTGRES_DB=imi_map_production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - LDAP=${LDAP}
      - RAILS_SERVE_STATIC_FILES=true
    depends_on:
      - postgresql
    volumes:
      - ./logc:/usr/src/app/log
    links:
      - postgresql
    ports:
      - 4000:80
#    volumes:
#      - ./rails/public:/usr/src/app/nginx-assets
#      - ./rails/public:/usr/src/app/public/assets
    restart: always
