version: '2'
services:
  postgresql:
    image: postgres:9.6.2-alpine
    container_name: postgresql-production
    environment:
      - POSTGRES_USER=imimaps
      - POSTGRES_PASSWORD=imimaps
      - POSTGRES_DB=imimaps
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  imimaps:
    image: imimapshtw/production:${TAG}
    container_name: imimaps-production
    environment:
      - POSTGRES_USER=imimaps
      - POSTGRES_PASSWORD=imimaps
      - POSTGRES_DB=imimaps
    depends_on:
      - postgresql
    links:
      - postgresql
    ports:
      - 4000:80
    volumes:
      - ./rails/public/uploads:/usr/src/app/public/uploads
