# frozen_string_literal: true

# this was generated by g scaffold due to the gem inherited_resources
# https://github.com/activeadmin/inherited_resources
# TBD: needs to be consolidated with our ApplicationResourceController
class CompleteInternshipsController < InheritedResources::Base
  authorize_resource

  private

  def complete_internship_params
    params.require(:complete_internship)
          .permit(:semester, :semester_of_study, :aep, :passed)
  end
end
