# frozen_string_literal: true

# this was generated by g scaffold due to the gem inherited_resources
# https://github.com/activeadmin/inherited_resources
# TBD: needs to be consolidated with our ApplicationResourceController
class CompleteInternshipsController < ApplicationResourceController
  # InheritedResources::Base
  # authorize_resource
  before_action :set_complete_internship, only: %i[show edit update destroy]

  def index
    @complete_internships = CompleteInternship.all
  end

  def show; end

  def new
    @complete_internship = CompleteInternship.new
  end

  def edit; end

  def create
    @complete_internship = CompleteInternship.new(complete_internship_params)

    respond_to do |format|
      if @complete_internship.save
        format.html do
          redirect_to @complete_internship,
                      notice: 'CompleteInternship was successfully created.'
        end
        format.json do
          render :show,
                 status: :created,
                 location: @complete_internship
        end
      else
        format.html { render :new }
        format.json do
          render json: @complete_internship.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @complete_internship.update(complete_internship_params)
        format.html do
          redirect_to @complete_internship,
                      notice: 'CompleteInternship was successfully updated.'
        end
        format.json do
          render :show,
                 status: :ok,
                 location: @complete_internship
        end
      else
        format.html { render :edit }
        format.json do
          render json: @complete_internship.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @complete_internship.destroy
    respond_to do |format|
      format.html do
        redirect_to complete_internships_url,
                    notice: 'CompleteInternship was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_complete_internship
    @complete_internship = CompleteInternship.find(params[:id])
  end

  def complete_internship_params
    params.require(:complete_internship)
          .permit(:semester, :semester_of_study, :aep, :passed)
  end
end
