# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CompleteInternshipsController, type: :controller do
  render_views

[:user, :admin].each do  | role |
  describe "for #{role}" do
  before :each do
     @current_user = login_with_factory(role)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompleteInternshipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let(:valid_attributes) { build(:complete_internship).attributes }
  # let(:invalid_attributes) {build(:complete_internship_incomplete).attributes}

  describe 'GET #index' do
    it 'returns a success response' do
      @current_user = login_as_admin
      create(:complete_internship)
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      complete_internship = create(:complete_internship)
      user = complete_internship.student.user
      sign_in user
      get :show, params: { id: complete_internship.to_param },
                 session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      login_as_student
      get :new,
          params: { complete_internship: valid_attributes },
          session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      complete_internship = create(:complete_internship)
      user = complete_internship.student.user
      sign_in user
      get :edit,
          params: { id: complete_internship.to_param },
          session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new CompleteInternship' do
        expect do
          login_as_student
          post :create,
               params: { complete_internship:
                 valid_attributes },
               session: valid_session
        end.to change(CompleteInternship, :count).by(1)
      end

      it 'redirects to the created complete_internship' do
        login_as_student
        post :create,
             params: { complete_internship:
               valid_attributes },
             session: valid_session
        expect(response).to redirect_to(CompleteInternship.last)
      end
    end

    context 'with invalid params' do
      it 'does not create a new CompleteInternship' do
        expect do
          post :create,
               params: { complete_internship:
                 { student_id: nil, semester_id: nil, semester_of_study: 3,
                   aep: nil, passed: nil } },
               session: valid_session
        end.to change(CompleteInternship, :count).by(0)
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        h = { student_id: 1, semester_id: 1, semester_of_study: 4, aep: false,
              passed: false }
        h['semester_of_study'] = 9
        h
      end

      it 'updates the requested complete_internship' do
        complete_internship = create(:complete_internship)
        user = complete_internship.student.user
        sign_in user
        put :update,
            params: { id: complete_internship.to_param,
                      complete_internship: new_attributes },
            session: valid_session
        complete_internship.reload
        expect(complete_internship.semester_of_study).to eq 9
      end

      it 'redirects to the complete_internship' do
        complete_internship = create(:complete_internship)
        user = complete_internship.student.user
        sign_in user
        put :update,
            params: { id: complete_internship.to_param,
                      complete_internship: new_attributes },
            session: valid_session
        expect(response).to redirect_to(complete_internship)
      end
    end

    #  context 'with invalid params' do
    #    it "returns a success response (i.e. to display the 'edit' template)"
    # do
    #      complete_internship = CompleteInternship.create! valid_attributes
    #      put :update,
    #          params: { id: complete_internship.to_param,
    #                    complete_internship: invalid_attributes },
    #          session: valid_session
    #      expect(response).to be_successful
    #    end
    #  end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested complete_internship' do
      complete_internship = create(:complete_internship)
      login_as_admin
      expect do
        delete :destroy,
               params: { id: complete_internship.to_param },
               session: valid_session
      end.to change(CompleteInternship, :count).by(-1)
    end

    it 'redirects to the complete_internships list' do
      complete_internship = create(:complete_internship)
      login_as_admin
      delete :destroy,
             params: { id: complete_internship.to_param },
             session: valid_session
      expect(response).to redirect_to(complete_internships_url)
    end
  end
end
end
end
