echo "DEPLOYMENT_DOCKER_ORGANISATION: $DEPLOYMENT_DOCKER_ORGANISATION"
echo "DEPLOYMENT_ENVIRONMENT: $DEPLOYMENT_ENVIRONMENT"
echo "DEPLOYMENT_TAG: $DEPLOYMENT_TAG"

echo "TRAVIS [${TRAVIS}]"
echo "TRAVIS_BRANCH [${TRAVIS_BRANCH}]"
echo "TRAVIS_COMMIT [${TRAVIS_COMMIT}]"
echo "TRAVIS_EVENT_TYPE [${TRAVIS_EVENT_TYPE}]"
echo "TRAVIS_PULL_REQUEST" [${TRAVIS_PULL_REQUEST}]
echo "TRAVIS_TAG [${TRAVIS_TAG}]"
